version: "1"
env_files:
  - .env
profile_dirs:
  - profiles
services:
  postgres:
    profile: postgres/native
  events-api:
    profile: bus/api/events/postgres
    depends_on:
      - postgres
  repos-integration:
    profile: bus/integration/repos/local
    depends_on:
      - events-api
  workers-integration:
    profile: bus/integration/workers/direct
    depends_on:
      - events-api
      - repos-integration
  tasks-integration:
    profile: bus/integration/tasks/local
    depends_on:
      - events-api
  bus-api:
    profile: bus/api/tasks-workers
    depends_on:
      - events-api
      - workers-integration
      - tasks-integration
