version: "1"
env_files:
  - .env
profile_dirs:
  - services/profiles
services:
  postgres:
    profile: postgres-native
  events-api:
    profile: bus-events-api-postgres
    depends_on:
      - postgres
  repos-integration:
    profile: bus-integration-repos-local
    depends_on:
      - events-api
  workers-integration:
    profile: bus-integration-workers-direct
    depends_on:
      - events-api
      - repos-integration
  bus-api:
    profile: bus-api-workers
    depends_on:
      - events-api
      - workers-integration
