#!/bin/sh
set -eu

# Proves the image-backed SSH-Docker path with the real Codex App Server
# backend on the remote host. This is the no-edit readiness smoke before
# trusting remote workers with writable task branches.

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

PROMPT=${BUS_SSH_DOCKER_CODEX_SMOKE_PROMPT:-SSH-Docker real Codex smoke: do not edit files. Inspect /workspace/bus-dev/go.mod, report the module path in one sentence, and finish with app_server_closeout JSON where task_complete=true, changed_files=[], plan_closed=false, no_matching_plan_item=true, no_matching_plan_reason explains this is a read-only smoke, required_checks includes the go.mod inspection, and remaining_blockers=[]. Do not run bus task close; the bridge will publish the terminal event. If Bus Notes are unavailable, state that as non-blocking evidence, not as a blocker.}
TIMEOUT=${BUS_SSH_DOCKER_CODEX_SMOKE_WAIT_TIMEOUT:-15m}
START_TIMEOUT=${BUS_SSH_DOCKER_CODEX_SMOKE_START_TIMEOUT:-5m}
WORKER_PROFILE=${BUS_SSH_DOCKER_CODEX_SMOKE_WORKER_PROFILE:-}
CODEX_MODEL=${BUS_SSH_DOCKER_CODEX_SMOKE_MODEL:-}
REASONING_EFFORT=${BUS_SSH_DOCKER_CODEX_SMOKE_REASONING_EFFORT:-}
CODEX_ARGS_JSON=${BUS_SSH_DOCKER_CODEX_SMOKE_ARGS_JSON:-}
WORKER_SANDBOX=${BUS_SSH_DOCKER_CODEX_SMOKE_WORKER_SANDBOX:-${BUS_SSH_DOCKER_CODEX_SMOKE_CODEX_SANDBOX:-}}
CODEX_NETWORK_ACCESS=${BUS_SSH_DOCKER_CODEX_SMOKE_CODEX_NETWORK_ACCESS:-}
WORKER_CAP_ADD=${BUS_SSH_DOCKER_CODEX_SMOKE_WORKER_CAP_ADD:-}
AUTH_MODE=${BUS_SSH_DOCKER_CODEX_SMOKE_AUTH_MODE:-chatgpt-subscription}
CREDENTIAL_SOURCE_KIND=${BUS_SSH_DOCKER_CODEX_SMOKE_CREDENTIAL_SOURCE_KIND:-}
CREDENTIAL_SOURCE_REF=${BUS_SSH_DOCKER_CODEX_SMOKE_CREDENTIAL_SOURCE_REF:-}
EVIDENCE_DIR=${BUS_SSH_DOCKER_CODEX_SMOKE_EVIDENCE_DIR:-}

BUS_SSH_DOCKER_SMOKE_AGENT_BACKEND=codex-appserver \
BUS_SSH_DOCKER_SMOKE_WORKER_PROFILE="$WORKER_PROFILE" \
BUS_SSH_DOCKER_SMOKE_CODEX_MODEL="$CODEX_MODEL" \
BUS_SSH_DOCKER_SMOKE_REASONING_EFFORT="$REASONING_EFFORT" \
BUS_SSH_DOCKER_SMOKE_CODEX_ARGS_JSON="$CODEX_ARGS_JSON" \
BUS_SSH_DOCKER_SMOKE_WORKER_SANDBOX="$WORKER_SANDBOX" \
BUS_SSH_DOCKER_SMOKE_CODEX_NETWORK_ACCESS="$CODEX_NETWORK_ACCESS" \
BUS_SSH_DOCKER_SMOKE_WORKER_CAP_ADD="$WORKER_CAP_ADD" \
BUS_SSH_DOCKER_SMOKE_AUTH_MODE="$AUTH_MODE" \
BUS_SSH_DOCKER_SMOKE_CREDENTIAL_SOURCE_KIND="$CREDENTIAL_SOURCE_KIND" \
BUS_SSH_DOCKER_SMOKE_CREDENTIAL_SOURCE_REF="$CREDENTIAL_SOURCE_REF" \
BUS_SSH_DOCKER_SMOKE_WORKTREE=false \
BUS_SSH_DOCKER_SMOKE_COMMIT=false \
BUS_SSH_DOCKER_SMOKE_START_TIMEOUT="$START_TIMEOUT" \
BUS_SSH_DOCKER_SMOKE_WAIT_TIMEOUT="$TIMEOUT" \
BUS_SSH_DOCKER_SMOKE_PROMPT="$PROMPT" \
BUS_SSH_DOCKER_SMOKE_EVIDENCE_DIR="$EVIDENCE_DIR" \
"$ROOT/scripts/test-ssh-docker-image-smoke.sh"
